
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 11 09:56:38 COT 2015
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int NUMEROS = 6;
  public static final int DIGITOSORO = 5;
  public static final int DIGITOSPICHINCHA = 4;
  public static final int CARACTER = 2;
  public static final int DIGITOSLOJA = 3;
  public static final int EOF = 0;
}

